/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: MADE.COM (https://sketchfab.com/made-it)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/jory-modular-shelves-walnut-and-oak-433546ba6deb4fbc99105ff281f5aca7
Title: Jory Modular Shelves, Walnut and Oak
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 90]}>
          <group position={[0, -16.617, 83.591]}>
            <mesh geometry={nodes.STEEL.geometry} material={materials.STEEL} />
            <mesh geometry={nodes.STEEL_BLACK.geometry} material={materials.EnvironmentAmbientLight} />
            <mesh geometry={nodes.OAK.geometry} material={materials.material} />
            <mesh geometry={nodes.WALNUT.geometry} material={materials.WALNUT} />
          </group>
        </group>
        <mesh geometry={nodes.FLOOR.geometry} material={materials.FLOOR} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
